DROP TABLE IF EXISTS TBL_TOKENS;
  
CREATE TABLE TBL_TOKENS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  access_token VARCHAR(250) NOT NULL,
  token_type VARCHAR(250) NOT NULL,
  expires_in VARCHAR(250) DEFAULT NULL,
  scope VARCHAR(250) DEFAULT NULL
);