DROP TABLE IF EXISTS TOKEN;
  
CREATE TABLE TOKEN (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  access_token VARCHAR(250) NOT NULL,
  token_type VARCHAR(250) DEFAULT NULL,
  expires_in VARCHAR(250) DEFAULT NULL,
  scope VARCHAR(250) DEFAULT NULL
);